### ISSUE TITLE
Kubic ISO does not work (creating VMware VM)

### ISSUE THREAD

**Issue by putztzu** [kubic-project/caasp-devenv#10]
Not sure if this is a proper place to post,
According to the SUSE caasp-beta team, their mailing list and other "support" don't support Kubic which is considered separate and "community."
And, I can't find a project or repository specifically  for the Kubic ISO.
Also, unable to find an OBS project for Kubic (although my search capability may be poor).

So, I cannot find any Kubic support or reporting places except this github Kubic project as a whole.

1. The Kubic ISO install results in only a partial install and boots only into Recovery Mode without networking.
2. Lack of documentation, in particular just for initial deployment, configuration and updating. In particular, it should be no surprise the **transactional-update** command is new to me, I don't know if repos need to be configured (or how). There is no MAN page or sufficient "--help" to get it to work, or is it supposed to automatically point to SUSE caasp-beta repos? But, even if this is better addressed, I assume that this requires a working networking connection.

TIA,
Tony

**Comment by PI-Victor** [comment]
closed in favor of https://github.com/kubic-project/community/issues/4 we can continue talking there.
